# Generated by Django 3.0 on 2019-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='number_of_searches',
            field=models.IntegerField(default=0),
        ),
    ]
