# Generated by Django 3.0 on 2019-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('searches', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('searches', models.IntegerField(default=0)),
                ('release_date', models.DateField()),
                ('overview', models.TextField(max_length=255)),
                ('rate', models.FloatField(default=0.0)),
                ('genres', models.ManyToManyField(related_name='genre_movies', to='movies.Genre')),
            ],
        ),
    ]
